/* One-time: pulls the latin + latin-ext woff2 subsets from Google Fonts into
   assets/fonts/ and writes assets/css/fonts.css with self-hosted @font-face rules.
   Re-run only if you change which weights the site uses. */
const fs = require('fs');
const path = require('path');
const https = require('https');

const SPEC = 'https://fonts.googleapis.com/css2?family=Archivo:wght@500;700;800&family=Inter:wght@400;500;600&display=swap';
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const KEEP = ['latin', 'latin-ext'];
const ROOT = path.join(__dirname, '..');

const get = (url, binary) => new Promise((resolve, reject) => {
  https.get(url, { headers: { 'User-Agent': UA } }, res => {
    if (res.statusCode !== 200) return reject(new Error(url + ' → ' + res.statusCode));
    const chunks = [];
    res.on('data', c => chunks.push(c));
    res.on('end', () => resolve(binary ? Buffer.concat(chunks) : Buffer.concat(chunks).toString('utf8')));
  }).on('error', reject);
});

(async () => {
  const css = await get(SPEC, false);
  const blocks = css.split('/*').slice(1).map(b => '/*' + b);
  const out = [
    '/* Self-hosted subsets of Archivo and Inter (SIL Open Font License 1.1).',
    '   Generated by tools/fetch-fonts.js — do not hand-edit. */',
    '',
  ];
  let n = 0;

  for (const block of blocks) {
    const subset = (block.match(/^\/\*\s*([a-z-]+)\s*\*\//) || [])[1];
    if (!KEEP.includes(subset)) continue;

    const family = (block.match(/font-family:\s*'([^']+)'/) || [])[1];
    const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1];
    const url = (block.match(/url\((https:[^)]+)\)/) || [])[1];
    if (!family || !weight || !url) continue;

    const file = `${family.toLowerCase()}-${weight}-${subset}.woff2`;
    fs.writeFileSync(path.join(ROOT, 'assets', 'fonts', file), await get(url, true));
    n++;

    out.push(block
      .replace(/^\/\*.*?\*\/\s*/s, '')
      .replace(/url\(https:[^)]+\)/, `url(../fonts/${file})`)
      .trim());
    out.push('');
  }

  fs.writeFileSync(path.join(ROOT, 'assets', 'css', 'fonts.css'), out.join('\n'));
  console.log(`downloaded ${n} woff2 files → assets/fonts/, wrote assets/css/fonts.css`);
})();
